Admin/Backend/backend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.decorators import login_required
from .views import MyPasswordChangeView, MyPasswordSetView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    
    # menu
    path('',include("menu.urls")),
    
    
    # myaccounts
    path('myaccounts/',include("myaccounts.urls")),
    
    # auth-account
    path('account/', include('allauth.urls')),
    
    path(
        "account/password/change/",
        login_required(MyPasswordChangeView.as_view()),
        name="account_change_password",
    ),
    path(
        "account/password/set/",
        login_required(MyPasswordSetView.as_view()),
        name="account_set_password",
    ),
    
    
]

Admin/Backend/menu/urls.py
from django.urls import path
from menu.views import (
    
    dashboard_view,
    product_list_view,
    product_grid_view,
    product_overview_view,
    product_create_view,
    categories_view,
    sub_categories_view,
    
    orders_list_view,
    orders_overview_view,
    
    calendar_view,
    
    seller_list_view,
    seller_grid_view,
    seller_overview_view,
    
    invoice_list_view,
    invoice_details_view,
    invoice_create_view,
    
    users_list_view,
    
    shipping_list_view,
    shipments_view,
    
    coupons_view,
    reviews_rating_view,
    brands_view,
    statistics_view,
    transactions_view,
    currency_rates_view,
)

app_name = 'menu'

urlpatterns = [
    
    path('',view=dashboard_view,name='dashboard'),
    path('product/list_view',view=product_list_view,name='product.product_list_view'),
    path('product/grid_view',view=product_grid_view,name='product.product_grid_view'),
    path('product/product_overview',view=product_overview_view,name='product.product_overview'),
    path('product/product_create',view=product_create_view,name='product.product_create'),
    path('product/categories',view=categories_view,name='product.categories'),
    path('product/sub_categories',view=sub_categories_view,name='product.sub_categories'),
    
    path('orders/list_view',view=orders_list_view,name='orders.list_view'),
    path('orders/overview',view=orders_overview_view,name='orders.overview_view'),
    
    path('calendar',view=calendar_view,name='calendar'),
    
    path('sellers/list_view',view=seller_list_view,name='sellers.list_view'),
    path('sellers/grid_view',view=seller_grid_view,name='sellers.grid_view'),
    path('sellers/overview',view=seller_overview_view,name='sellers.seller_overview_view'),
    
    path('invoice/list_view',view=invoice_list_view,name='invoice.list_view'),
    path('invoice/details_view',view=invoice_details_view,name='invoice.details_view'),
    path('invoice/create_invoice',view=invoice_create_view,name='invoice.create_invoice'),
    
    path('users_list',view=users_list_view,name='users_list'),
    
    path('shipping/list_view',view=shipping_list_view,name='shipping.list_view'),
    path('shipping/shipments',view=shipments_view,name='shipping.shipments'),
    
    path('coupons',view=coupons_view,name='coupons'),
    
    path('reviews_rating',view=reviews_rating_view,name='reviews_rating'),
    
    path('brands',view=brands_view,name='brands'),
    
    path('statistics',view=statistics_view,name='statistics'),
    
    path('localization/transactions',view=transactions_view,name='localization.transactions'),
    
    path('localization/currency_rates',view=currency_rates_view,name='localization.currency_rates'),
    
    
]

Admin/Backend/myaccounts/urls.py
from django.urls import path
from myaccounts.views import (
    
    myaccount_view,
    account_settings_view,
    signup_view,
    signin_view,
    password_reset_view,
    password_change_view,
    success_msg_view,
    twostep_verification_view,
    logout_view,
    error404_view,
    error500_view,
    coming_soon_view,
)

app_name = 'myaccounts'

urlpatterns = [
    
    path("account",view=myaccount_view,name="account"),
    path("account_settings",view=account_settings_view,name="account_settings"),
    path("signup",view=signup_view,name="signup"),
    path("signin",view=signin_view,name="signin"),
    path("password_reset",view=password_reset_view,name="password_reset"),
    path("password_change",view=password_change_view,name="password_change"),
    path("success_msg",view=success_msg_view,name="success_msg"),
    path("twostep_verification",view=twostep_verification_view,name="twostep_verification"),
    path("logout",view=logout_view,name="logout"),
    path("error404",view=error404_view,name="error404"),
    path("error500",view=error500_view,name="error500"),
    path("coming_soon",view=coming_soon_view,name="coming_soon"),
]

Admin/Backend/myaccounts/models.py
from django.db import models

# Create your models here.

Admin/Backend/myaccounts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class MyaccountView(TemplateView):
    pass 

myaccount_view = MyaccountView.as_view(template_name = "myaccounts/account.html")
account_settings_view = MyaccountView.as_view(template_name = "myaccounts/account-settings.html")
signup_view = MyaccountView.as_view(template_name = "myaccounts/auth-signup-basic.html")
signin_view = MyaccountView.as_view(template_name = "myaccounts/auth-signin-basic.html")
password_reset_view = MyaccountView.as_view(template_name = "myaccounts/auth-pass-reset-basic.html")
password_change_view = MyaccountView.as_view(template_name = "myaccounts/auth-pass-change-basic.html")
success_msg_view = MyaccountView.as_view(template_name = "myaccounts/auth-success-msg-basic.html")
twostep_verification_view = MyaccountView.as_view(template_name = "myaccounts/auth-twostep-basic.html")
logout_view = MyaccountView.as_view(template_name = "myaccounts/auth-logout-basic.html")
error404_view = MyaccountView.as_view(template_name = "myaccounts/auth-404.html")
error500_view = MyaccountView.as_view(template_name = "myaccounts/auth-500.html")
coming_soon_view = MyaccountView.as_view(template_name = "myaccounts/coming-soon.html")

Admin/Backend/templates/myaccounts/auth-logout-basic.html
{% load static %}
<!doctype html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="light" data-sidebar-size="lg" data-sidebar-image="none" data-preloader="disable" data-body-image="none">
    <head>
        <meta charset="utf-8">
        <title>Log Out | Toner eCommerce + Admin HTML Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="eCommerce + Admin HTML Template" name="description">
        <meta content="Themesbrand" name="author">
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

        <!-- Layout config Js -->
        <script src="{% static 'js/layout.js' %}"></script>
        <!-- Bootstrap Css -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <!-- Icons Css -->
        <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css">
        <!-- App Css-->
        <link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css">
        <!-- custom Css-->
        <link href="{% static 'css/custom.min.css' %}" rel="stylesheet" type="text/css">

    </head>

    <body>

        <section class="auth-page-wrapper position-relative bg-light min-vh-100 d-flex align-items-center justify-content-between">
            <div class="auth-header position-fixed top-0 start-0 end-0 bg-body">
                <div class="container-fluid">
                    <div class="row justify-content-between align-items-center">
                        <div class="col-2">
                            <a class="navbar-brand mb-2 mb-sm-0" href="{% url 'menu:dashboard' %}">
                                <img src="{% static 'images/logo-dark.png' %}" class="card-logo card-logo-dark" alt="logo dark" height="22">
                                <img src="{% static 'images/logo-light.png' %}" class="card-logo card-logo-light" alt="logo light" height="22">
                            </a>
                        </div><!---end col-->
                        <div class="col-auto">
                            <ul class="list-unstyled hstack gap-2 mb-0">
                                <li class="me-md-3">
                                    <a href="#!" class="text-body fw-medium fs-15">Become a Selling</a>
                                </li>
                                <li class="d-none d-md-block">
                                    <a href="#!" class="btn btn-soft-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-google-play align-middle me-1"></i> Download App
                                    </a>
                                </li>
                                <li class="d-none d-md-block">
                                    <a href="#!" class="btn btn-soft-primary" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-apple align-middle me-1"></i> Download App
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div><!--end row-->
                </div><!--end container-fluid-->
            </div>
            <div class="w-100">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="auth-card mx-lg-3">
                                <div class="card border-0 mb-0">
                                    <div class="card-header bg-primary border-0">
                                        <div class="row">
                                            <div class="col-lg-4 col-3">
                                                <img src="{% static 'images/auth/img-1.png' %}" alt="" class="img-fluid">
                                            </div>
                                            <div class="col-lg-8 col-9">
                                                <h1 class="text-white lh-base fw-lighter">You are Logged Out</h1>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-body text-center">

                                        <div class="mb-4">
                                            <img src="{% static 'images/users/avatar-1.jpg' %}" alt="" class="avatar-md rounded-circle">
                                        </div>

                                        <p class="text-muted fs-15">Thank you for using <span class="fw-semibold">Toner</span> admin template</p>

                                        <div>
                                            <a href="{% url 'myaccounts:signin' %}" class="btn btn-primary w-100">Sign In</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!--end col-->
                    </div><!--end row-->
                </div><!--end container-->

                <footer class="footer">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="text-center">
                                    <p class="mb-0 text-muted">©
                                        <script>document.write(new Date().getFullYear())</script> Toner. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </section>

        
        <!-- JAVASCRIPT -->
        <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'libs/simplebar/dist/simplebar.min.js' %}"></script>
        <script src="{% static 'js/plugins.js' %}"></script>

    </body>

</html>

Admin/Backend/templates/myaccounts/auth-pass-reset-basic.html
{% load static %}
<!doctype html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="light" data-sidebar-size="lg" data-sidebar-image="none" data-preloader="disable" data-body-image="none">
    <head>
        <meta charset="utf-8">
        <title>Reset Passowrd | Toner eCommerce + Admin HTML Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="eCommerce + Admin HTML Template" name="description">
        <meta content="Themesbrand" name="author">
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

        <!-- Layout config Js -->
        <script src="{% static 'js/layout.js' %}"></script>
        <!-- Bootstrap Css -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <!-- Icons Css -->
        <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css">
        <!-- App Css-->
        <link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css">
        <!-- custom Css-->
        <link href="{% static 'css/custom.min.css' %}" rel="stylesheet" type="text/css">

    </head>

    <body>

        <section class="auth-page-wrapper position-relative bg-light min-vh-100 d-flex align-items-center justify-content-between">
            <div class="auth-header position-fixed top-0 start-0 end-0 bg-body">
                <div class="container-fluid">
                    <div class="row justify-content-between align-items-center">
                        <div class="col-2">
                            <a class="navbar-brand mb-2 mb-sm-0" href="{% url 'menu:dashboard' %}">
                                <img src="{% static 'images/logo-dark.png' %}" class="card-logo card-logo-dark" alt="logo dark" height="22">
                                <img src="{% static 'images/logo-light.png' %}" class="card-logo card-logo-light" alt="logo light" height="22">
                            </a>
                        </div><!---end col-->
                        <div class="col-auto">
                            <ul class="list-unstyled hstack gap-2 mb-0">
                                <li class="me-md-3">
                                    <a href="#!" class="text-body fw-medium fs-15">Become a Selling</a>
                                </li>
                                <li class="d-none d-md-block">
                                    <a href="#!" class="btn btn-soft-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-google-play align-middle me-1"></i> Download App
                                    </a>
                                </li>
                                <li class="d-none d-md-block">
                                    <a href="#!" class="btn btn-soft-primary" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-apple align-middle me-1"></i> Download App
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div><!--end row-->
                </div><!--end container-fluid-->
            </div>
            <div class="w-100">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="auth-card mx-lg-3">
                                <div class="card border-0 mb-0">
                                    <div class="card-header bg-primary border-0">
                                        <div class="row">
                                            <div class="col-lg-4 col-3">
                                                <img src="{% static 'images/auth/img-1.png' %}" alt="" class="img-fluid">
                                            </div>
                                            <div class="col-lg-8 col-9">
                                                <h1 class="text-white lh-base fw-lighter">Forgot Password?</h1>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <p class="text-muted fs-15">Reset password with Toner.</p>

                                        <div class="alert alert-borderless alert-warning text-center mb-2 mx-2" role="alert">
                                            Enter your email and instructions will be sent to you!
                                        </div>
                                        <div class="p-2">
                                            <form>
                                                <div class="mb-4">
                                                    <label for="email" class="form-label">Email</label>
                                                    <input type="email" class="form-control" id="email" placeholder="Enter your email or username" required />
                                                </div>
                                        
                                                <div class="text-center mt-4">
                                                    <button class="btn btn-primary w-100" type="submit">Send Reset Link</button>
                                                </div>
                                            </form><!-- end form -->
                                        </div>
                                        <div class="mt-4 text-center">
                                            <p class="mb-0">Wait, I remember my password... <a href="{% url 'myaccounts:signin' %}" class="fw-semibold text-primary text-decoration-underline"> Click here </a> </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!--end col-->
                    </div><!--end row-->
                </div><!--end container-->

                <footer class="footer">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="text-center">
                                    <p class="mb-0 text-muted">©
                                        <script>document.write(new Date().getFullYear())</script> Toner. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </section>

        <!-- JAVASCRIPT -->
        <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'libs/simplebar/dist/simplebar.min.js' %}"></script>
        <script src="{% static 'js/plugins.js' %}"></script>

        <script src="{% static 'js/pages/password-addon.init.js' %}"></script>

    </body>

</html>

Admin/Backend/templates/myaccounts/auth-signin-basic.html
{% load static %}
<!doctype html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="light" data-sidebar-size="lg" data-sidebar-image="none" data-preloader="disable" data-body-image="none">
    <head>
        <meta charset="utf-8">
        <title>Sign in | Toner eCommerce + Admin HTML Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="eCommerce + Admin HTML Template" name="description">
        <meta content="Themesbrand" name="author">
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

        <!-- Layout config Js -->
        <script src="{% static 'js/layout.js' %}"></script>
        <!-- Bootstrap Css -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <!-- Icons Css -->
        <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css">
        <!-- App Css-->
        <link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css">
        <!-- custom Css-->
        <link href="{% static 'css/custom.min.css' %}" rel="stylesheet" type="text/css">

    </head>

    <body>

        <section class="auth-page-wrapper position-relative bg-light min-vh-100 d-flex align-items-center justify-content-between">
            <div class="auth-header position-fixed top-0 start-0 end-0 bg-body">
                <div class="container-fluid">
                    <div class="row justify-content-between align-items-center">
                        <div class="col-2">
                            <a class="navbar-brand mb-2 mb-sm-0" href="{% url 'menu:dashboard' %}">
                                <img src="{% static 'images/logo-dark.png' %}" class="card-logo card-logo-dark" alt="logo dark" height="22">
                                <img src="{% static 'images/logo-light.png' %}" class="card-logo card-logo-light" alt="logo light" height="22">
                            </a>
                        </div><!---end col-->
                        <div class="col-auto">
                            <ul class="list-unstyled hstack gap-2 mb-0">
                                <li class="me-md-3">
                                    <a href="#!" class="text-body fw-medium fs-15">Become a Selling</a>
                                </li>
                                <li class="d-none d-md-block">
                                    <a href="#!" class="btn btn-soft-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-google-play align-middle me-1"></i> Download App
                                    </a>
                                </li>
                                <li class="d-none d-md-block">
                                    <a href="#!" class="btn btn-soft-primary" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-apple align-middle me-1"></i> Download App
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div><!--end row-->
                </div><!--end container-fluid-->
            </div>
            <div class="w-100">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="auth-card mx-lg-3">
                                <div class="card border-0 mb-0">
                                    <div class="card-header bg-primary border-0">
                                        <div class="row">
                                            <div class="col-lg-4 col-3">
                                                <img src="{% static 'images/auth/img-1.png' %}" alt="" class="img-fluid">
                                            </div>
                                            <div class="col-lg-8 col-9">
                                                <h1 class="text-white lh-base fw-lighter">Join Our Toner Store</h1>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <p class="text-muted fs-15">Sign in to continue to Toner.</p>
                                        <div class="p-2">
                                            <form action="{% url 'menu:dashboard' %}">
                
                                                <div class="mb-3">
                                                    <label for="username" class="form-label">Username</label>
                                                    <input type="text" class="form-control" id="username" placeholder="Enter username">
                                                </div>
                
                                                <div class="mb-3">
                                                    <div class="float-end">
                                                        <a href="{% url 'myaccounts:password_reset' %}" class="text-muted">Forgot password?</a>
                                                    </div>
                                                    <label class="form-label" for="password-input">Password</label>
                                                    <div class="position-relative auth-pass-inputgroup mb-3">
                                                        <input type="password" class="form-control pe-5 password-input" placeholder="Enter password" id="password-input">
                                                        <button class="btn btn-link position-absolute end-0 top-0 text-decoration-none text-muted password-addon" type="button" id="password-addon"><i class="ri-eye-fill align-middle"></i></button>
                                                    </div>
                                                </div>
                
                                                <div class="form-check">
                                                    <input class="form-check-input" type="checkbox" value="" id="auth-remember-check">
                                                    <label class="form-check-label" for="auth-remember-check">Remember me</label>
                                                </div>
                
                                                <div class="mt-4">
                                                    <button class="btn btn-primary w-100" type="submit">Sign In</button>
                                                </div>
                
                                                <div class="mt-4 pt-2 text-center">
                                                    <div class="signin-other-title">
                                                        <h5 class="fs-13 mb-4 title">Sign In with</h5>
                                                    </div>
                                                    <div class="pt-2 hstack gap-2 justify-content-center">
                                                        <button type="button" class="btn btn-soft-primary btn-icon"><i class="ri-facebook-fill fs-16"></i></button>
                                                        <button type="button" class="btn btn-soft-danger btn-icon"><i class="ri-google-fill fs-16"></i></button>
                                                        <button type="button" class="btn btn-soft-dark btn-icon"><i class="ri-github-fill fs-16"></i></button>
                                                        <button type="button" class="btn btn-soft-info btn-icon"><i class="ri-twitter-fill fs-16"></i></button>
                                                    </div>
                                                </div>
                                            </form>
                
                                            <div class="text-center mt-5">
                                                <p class="mb-0">Don't have an account ? <a href="{% url 'myaccounts:signup' %}" class="fw-semibold text-secondary text-decoration-underline"> SignUp</a> </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!--end col-->
                    </div><!--end row-->
                </div><!--end container-->
                
                <footer class="footer">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="text-center">
                                    <p class="mb-0 text-muted">©
                                        <script>document.write(new Date().getFullYear())</script> Toner. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </section>
        
        <!-- JAVASCRIPT -->
        <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'libs/simplebar/dist/simplebar.min.js' %}"></script>
        <script src="{% static 'js/plugins.js' %}"></script>

        <script src="{% static 'js/pages/password-addon.init.js' %}"></script>

    </body>

</html>