Admin/Frontend/dashboard/urls.py
from django.urls import path
from dashboard.views import(
    
    dashboard_view,
    watch_main_layout_view,
    modern_fashion_view,
    trend_fashion_view,
    
    contact_us_view,
)

app_name ='dashboard'

urlpatterns = [
    
    path('',view=dashboard_view,name='dashboard'),
    path('watch_main_layout',view=watch_main_layout_view,name='watch_main_layout'),
    path('modern_fashion',view=modern_fashion_view,name='modern_fashion'),
    path('trend_fashion',view=trend_fashion_view,name='trend_fashion'),
    
    
    
    path('contact_us',view=contact_us_view,name='contact_us'),
    
]

Admin/Frontend/frontend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.decorators import login_required
from .views import MyPasswordChangeView, MyPasswordSetView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    
    # dashboard
    path('',include("dashboard.urls")),
    
    # catalog
    path('catalog/',include("catalog.urls")),

    # shop
    path('shop/',include("shop.urls")),
    
    # pages
    path('pages/',include("pages.urls")),
    
    # auth-account
    path('account/', include('allauth.urls')),
    
    path(
        "account/password/change/",
        login_required(MyPasswordChangeView.as_view()),
        name="account_change_password",
    ),
    path(
        "account/password/set/",
        login_required(MyPasswordSetView.as_view()),
        name="account_set_password",
    ),
]

Admin/Frontend/shop/urls.py
from django.urls import path
from shop.views import(
    
    address_view,
    track_order_view,
    payment_view,
    review_view,
    confirmation_view,
    order_history_view,
    
    shop_cart_view,
    checkout_view,
    wishlist_view,
)

app_name ='shop'

urlpatterns = [
    
    # checkout pages
    path('address',view=address_view,name='address_view'),
    path('track_order',view=track_order_view,name='track_order_view'),
    path('payment',view=payment_view,name='payment_view'),
    path('review',view=review_view,name='review_view'),
    path('confirmation',view=confirmation_view,name='confirmation_view'),
    path('order_history',view=order_history_view,name='order_history_view'),
    
    # support
    path('shop_cart',view=shop_cart_view,name='shop_cart_view'),
    path('checkout',view=checkout_view,name='checkout_view'),
    path('wishlist',view=wishlist_view,name='wishlist_view'),
    
]

Admin/Frontend/templates/pages/users/auth-404.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="light" data-footer="dark">
    <head>

        <meta charset="utf-8">
        <title>404 | Toner eCommerce + Admin HTML Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="eCommerce + Admin HTML Template" name="description">
        <meta content="Themesbrand" name="author">
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

        <!-- Bootstrap Css -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <!-- Icons Css -->
        <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css">
        <!-- App Css-->
        <link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css">
        <!-- custom Css-->
        <link href="{% static 'css/custom.min.css' %}" rel="stylesheet" type="text/css">

    </head>
    <body>
        <section class="auth-page-wrapper position-relative bg-light min-vh-100 d-flex align-items-center justify-content-between">
            <div class="auth-header position-fixed top-0 start-0 end-0 bg-body">
                <div class="container-fluid">
                    <div class="row justify-content-between align-items-center">
                        <div class="col-2">
                            <a href="{% url 'dashboard:dashboard' %}"><img src="{% static 'images/logo-dark.png' %}" alt="" height="24" /></a>
                        </div><!---end col-->
                        <div class="col-auto">
                            <ul class="list-unstyled hstack gap-2 mb-0">
                                <li class="me-md-3">
                                    <a href="#!" class="text-body fw-medium fs-15">Become a Selling</a>
                                </li>
                                <li class="d-none d-md-block">
                                    <a href="#!" class="btn btn-soft-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-google-play align-middle me-1"></i> Download App
                                    </a>
                                </li>
                                <li class="d-none d-md-block">
                                    <a href="#!" class="btn btn-soft-primary" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-apple align-middle me-1"></i> Download App
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div><!--end row-->
                </div><!--end container-fluid-->
            </div>
            <div class="w-100">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="auth-card mx-lg-3">
                                <div class="card border-0 mb-0">
                                    <div class="card-body text-center p-4">

                                        <div class="text-center px-sm-5 mx-5">
                                            <img src="{% static 'images/error400.png' %}" class="img-fluid" alt="">
                                        </div>
                                        <div class="mt-4 text-center pt-3">
                                            <div class="position-relative">
                                                <h4 class="fs-18 error-subtitle text-uppercase mb-0">Opps, page not found</h4>
                                                <p class="fs-15 text-muted mt-3">It will be as simple as Occidental in fact,
                                                    it will Occidental to an English person</p>
                                                <div class="mt-4">
                                                    <a href="{% url 'dashboard:dashboard' %}" class="btn btn-primary"><i class="mdi mdi-home me-1"></i>Back to home</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!--end col-->
                    </div><!--end row-->
                </div><!--end container-->

                <footer class="footer">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="text-center">
                                    <p class="mb-0 text-muted">©
                                        <script>document.write(new Date().getFullYear())</script> Toner. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </section>

        <!-- JAVASCRIPT -->
        <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'libs/simplebar/dist/simplebar.min.js' %}"></script>
        <script src="{% static 'js/plugins.js' %}"></script>

    </body>

</html>

Admin/Frontend/templates/pages/users/auth-500.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="light" data-footer="dark">
    <head>

        <meta charset="utf-8">
        <title>500 | Toner eCommerce + Admin HTML Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="eCommerce + Admin HTML Template" name="description">
        <meta content="Themesbrand" name="author">
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

        <!-- Bootstrap Css -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <!-- Icons Css -->
        <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css">
        <!-- App Css-->
        <link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css">
        <!-- custom Css-->
        <link href="{% static 'css/custom.min.css' %}" rel="stylesheet" type="text/css">

    </head>
    <body>

        <section class="auth-page-wrapper position-relative bg-light min-vh-100 d-flex align-items-center justify-content-between">
            <div class="auth-header position-fixed top-0 start-0 end-0 bg-body">
                <div class="container-fluid">
                    <div class="row justify-content-between align-items-center">
                        <div class="col-2">
                            <a href="{% url 'dashboard:dashboard' %}"><img src="{% static 'images/logo-dark.png' %}" alt="" height="24" /></a>
                        </div><!---end col-->
                        <div class="col-auto">
                            <ul class="list-unstyled hstack gap-2 mb-0">
                                <li class="me-md-3">
                                    <a href="#!" class="text-body fw-medium fs-15">Become a Selling</a>
                                </li>
                                <li class="d-none d-md-block">
                                    <a href="#!" class="btn btn-soft-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-google-play align-middle me-1"></i> Download App
                                    </a>
                                </li>
                                <li class="d-none d-md-block">
                                    <a href="#!" class="btn btn-soft-primary" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-apple align-middle me-1"></i> Download App
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div><!--end row-->
                </div><!--end container-fluid-->
            </div>
            <div class="w-100">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="auth-card mx-lg-3">
                                <div class="card border-0 mb-0">
                                    <div class="card-body text-center p-4">

                                        <div class="text-center px-sm-5 mx-5">
                                            <img src="{% static 'images/error500.png' %}" class="img-fluid" alt="">
                                        </div>
                                        <div class="mt-4 text-center pt-3">
                                            <div class="position-relative">
                                                <h4 class="fs-18 error-subtitle text-uppercase mb-0">Internal Server Error</h4>
                                                <p class="fs-15 text-muted mt-3">It will be as simple as Occidental in fact, it will Occidental to an English person</p>
                                                <div class="mt-4">
                                                    <a href="{% url 'dashboard:dashboard' %}" class="btn btn-primary"><i class="mdi mdi-home me-1"></i>Back to home</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!--end col-->
                    </div><!--end row-->
                </div><!--end container-->

                <footer class="footer">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="text-center">
                                    <p class="mb-0 text-muted">©
                                        <script>document.write(new Date().getFullYear())</script> Toner. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </section>

        
        <!-- JAVASCRIPT -->
        <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'libs/simplebar/dist/simplebar.min.js' %}"></script>
        <script src="{% static 'js/plugins.js' %}"></script>

    </body>

</html>

Admin/Frontend/templates/pages/users/auth-logout-basic.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="light" data-footer="dark">
    <head>

        <meta charset="utf-8">
        <title>Log Out | Toner eCommerce + Admin HTML Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="eCommerce + Admin HTML Template" name="description">
        <meta content="Themesbrand" name="author">
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

        <!-- Bootstrap Css -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <!-- Icons Css -->
        <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css">
        <!-- App Css-->
        <link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css">
        <!-- custom Css-->
        <link href="{% static 'css/custom.min.css' %}" rel="stylesheet" type="text/css">

    </head>
    <body>

        <section class="auth-page-wrapper position-relative bg-light min-vh-100 d-flex align-items-center justify-content-between">
            <div class="auth-header position-fixed top-0 start-0 end-0 bg-body">
                <div class="container-fluid">
                    <div class="row justify-content-between align-items-center">
                        <div class="col-2">
                            <a class="navbar-brand mb-2 mb-sm-0" href="{% url 'dashboard:dashboard' %}">
                                <img src="{% static 'images/logo-dark.png' %}" class="card-logo card-logo-dark" alt="logo dark" height="22">
                                <img src="{% static 'images/logo-light.png' %}" class="card-logo card-logo-light" alt="logo light" height="22">
                            </a>
                        </div><!---end col-->
                        <div class="col-auto">
                            <ul class="list-unstyled hstack gap-2 mb-0">
                                <li class="me-md-3">
                                    <a href="#!" class="text-body fw-medium fs-15">Become a Selling</a>
                                </li>
                                <li class="d-none d-md-block">
                                    <a href="#!" class="btn btn-soft-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-google-play align-middle me-1"></i> Download App
                                    </a>
                                </li>
                                <li class="d-none d-md-block">
                                    <a href="#!" class="btn btn-soft-primary" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-apple align-middle me-1"></i> Download App
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div><!--end row-->
                </div><!--end container-fluid-->
            </div>
            <div class="w-100">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="auth-card mx-lg-3">
                                <div class="card border-0 mb-0">
                                    <div class="card-header bg-primary border-0">
                                        <div class="row">
                                            <div class="col-lg-4 col-3">
                                                <img src="{% static 'images/auth/img-1.png' %}" alt="" class="img-fluid">
                                            </div>
                                            <div class="col-lg-8 col-9">
                                                <h1 class="text-white lh-base fw-lighter">You are Logged Out</h1>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-body text-center">

                                        <div class="mb-4">
                                            <img src="{% static 'images/users/avatar-1.jpg' %}" alt="" class="avatar-md rounded-circle">
                                        </div>

                                        <p class="text-muted fs-15">Thank you for using <span class="fw-semibold">Toner</span> admin template</p>

                                        <div>
                                            <a href="{% url 'pages:users.sign_in' %}" class="btn btn-primary w-100">Sign In</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!--end col-->
                    </div><!--end row-->
                </div><!--end container-->

                <footer class="footer">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="text-center">
                                    <p class="mb-0 text-muted">©
                                        <script>document.write(new Date().getFullYear())</script> Toner. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </section>

        
        <!-- JAVASCRIPT -->
        <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'libs/simplebar/dist/simplebar.min.js' %}"></script>
        <script src="{% static 'js/plugins.js' %}"></script>

    </body>

</html>

Admin/Frontend/templates/pages/users/auth-pass-change-basic.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="light" data-footer="dark">
    <head>

        <meta charset="utf-8">
        <title>Change Passowrd| Toner eCommerce + Admin HTML Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="eCommerce + Admin HTML Template" name="description">
        <meta content="Themesbrand" name="author">
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

        <!-- Bootstrap Css -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <!-- Icons Css -->
        <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css">
        <!-- App Css-->
        <link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css">
        <!-- custom Css-->
        <link href="{% static 'css/custom.min.css' %}" rel="stylesheet" type="text/css">

    </head>
    <body>

        <section class="auth-page-wrapper position-relative bg-light min-vh-100 d-flex align-items-center justify-content-between">
            <div class="auth-header position-fixed top-0 start-0 end-0 bg-body">
                <div class="container-fluid">
                    <div class="row justify-content-between align-items-center">
                        <div class="col-2">
                            <a class="navbar-brand mb-2 mb-sm-0" href="{% url 'dashboard:dashboard' %}">
                                <img src="{% static 'images/logo-dark.png' %}" class="card-logo card-logo-dark" alt="logo dark" height="22">
                                <img src="{% static 'images/logo-light.png' %}" class="card-logo card-logo-light" alt="logo light" height="22">
                            </a>
                        </div><!---end col-->
                        <div class="col-auto">
                            <ul class="list-unstyled hstack gap-2 mb-0">
                                <li class="me-md-3">
                                    <a href="#!" class="text-body fw-medium fs-15">Become a Selling</a>
                                </li>
                                <li class="d-none d-md-block">
                                    <a href="#!" class="btn btn-soft-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-google-play align-middle me-1"></i> Download App
                                    </a>
                                </li>
                                <li class="d-none d-md-block">
                                    <a href="#!" class="btn btn-soft-primary" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-apple align-middle me-1"></i> Download App
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div><!--end row-->
                </div><!--end container-fluid-->
            </div>
            <div class="w-100">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="auth-card mx-lg-3">
                                <div class="card border-0 mb-0">
                                    <div class="card-header bg-primary border-0">
                                        <div class="row">
                                            <div class="col-lg-4 col-3">
                                                <img src="{% static 'images/auth/img-1.png' %}" alt="" class="img-fluid">
                                            </div>
                                            <div class="col-lg-8 col-9">
                                                <h1 class="text-white lh-base fw-lighter">Create New Password</h1>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <p class="text-muted fs-15">Your new password must be different from previous used password.</p>

                                        <div class="p-2">
                                            <form action="{% url 'pages:users.sign_in' %}">
                                                <div class="mb-3">
                                                    <label class="form-label" for="password-input">Password</label>
                                                    <div class="position-relative auth-pass-inputgroup">
                                                        <input type="password" class="form-control pe-5 password-input" onpaste="return false" placeholder="Enter password" id="password-input" aria-describedby="passwordInput" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" required>
                                                        <button class="btn btn-link position-absolute end-0 top-0 text-decoration-none text-muted password-addon" type="button" id="password-addon"><i class="ri-eye-fill align-middle"></i></button>
                                                    </div>
                                                    <div id="passwordInput" class="form-text">Your password must be 8-20 characters long.</div>
                                                </div>

                                                <div class="mb-3">
                                                    <label class="form-label" for="confirm-password-input">Confirm Password</label>
                                                    <div class="position-relative auth-pass-inputgroup mb-3">
                                                        <input type="password" class="form-control pe-5 password-input" onpaste="return false" placeholder="Confirm password" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" id="confirm-password-input" required>
                                                        <button class="btn btn-link position-absolute end-0 top-0 text-decoration-none text-muted password-addon" type="button" id="confirm-password-input"><i class="ri-eye-fill align-middle"></i></button>
                                                    </div>
                                                </div>

                                                <div id="password-contain" class="p-3 bg-light mb-2 rounded">
                                                    <h5 class="fs-13">Password must contain:</h5>
                                                    <p id="pass-length" class="invalid fs-12 mb-2">Minimum <b>8 characters</b></p>
                                                    <p id="pass-lower" class="invalid fs-12 mb-2">At <b>lowercase</b> letter (a-z)</p>
                                                    <p id="pass-upper" class="invalid fs-12 mb-2">At least <b>uppercase</b> letter (A-Z)</p>
                                                    <p id="pass-number" class="invalid fs-12 mb-0">A least <b>number</b> (0-9)</p>
                                                </div>

                                                <div class="form-check form-check-primary">
                                                    <input class="form-check-input" type="checkbox" value="" id="auth-remember-check">
                                                    <label class="form-check-label" for="auth-remember-check">Remember me</label>
                                                </div>

                                                <div class="mt-4">
                                                    <button class="btn btn-primary w-100" type="submit">Reset Password</button>
                                                </div>

                                            </form>
                                        </div>
                                        <div class="mt-4 text-center">
                                            <p class="mb-0">Wait, I remember my password... <a href="{% url 'pages:users.sign_in' %}" class="fw-semibold text-primary text-decoration-underline"> Click here </a> </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!--end col-->
                    </div><!--end row-->
                </div><!--end container-->

                <footer class="footer">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="text-center">
                                    <p class="mb-0 text-muted">©
                                        <script>document.write(new Date().getFullYear())</script> Toner. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </section>

        <!-- JAVASCRIPT -->
        <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'libs/simplebar/dist/simplebar.min.js' %}"></script>
        <script src="{% static 'js/plugins.js' %}"></script>

        <!-- password-addon init -->
        <script src="{% static 'js/pages/passowrd-create.init.js' %}"></script>

    </body>

</html>